### ISSUE TITLE
onShutdown not invoked if EventProcessor is not started

### ISSUE THREAD

**Issue by zoltanmaric** [LMAX-Exchange/disruptor#111]
I have a situation where I have to flush my data ([described here](https://github.com/LMAX-Exchange/disruptor/issues/110)) after the last event is processed by my EventHandler.

My `EventHandler` now implements the `LifecycleAware` interface, and I do my flushing in its `onShutdown()` method as suggested. However, in my tests I ran into the situation that occasionally, the shutdown callback is not invoked because I shut down my disruptor before the `EventHandler` thread is started.

The documentation of the `Disruptor.shutdown()` method suggests that I have to make sure that all my events are published before invoking it. That is ensured in my case. The problem is that even though the events are all published, my `EventHandler` sometimes doesn't get started in time and it doesn't get a shutdown callback because of this.

Looking at the source, it seems that the reason is that the `hasBackLog()` method in the `shutdown(timeout, timeUnit)` method doesn't check the `cursor` for consumers that aren't running: 

``` java
    /**
     * Confirms if all messages have been consumed by all event processors
     */
    private boolean hasBacklog()
    {
        final long cursor = ringBuffer.getCursor();
        for (Sequence consumer : consumerRepository.getLastSequenceInChain(false))
        {
            if (cursor > consumer.get())
            {
                return true;
            }
        }
        return false;
    }
```

I suggest adding a `shutdown(includeStopped)` overload method which invokes a `hasBacklog(includeStopped)` overload to also check for threads that are not yet running. This may not be the best way to fix it, but I think it helps understand what my issue is.

**Comment by mikeb01** [comment]
I'll have a look at the suggestion.  Often I'll use a `CountDownLatch` to ensure that an `EventHandler` has started.

```Java
CountDownLatch latch = new CountDownLatch(1);

@Override
public void onStart()
{
    latch.countDown();
}

public void waitOnStart() throws InterruptedException
{
    latch.await();
}
```

**Comment by zoltanmaric** [comment]
Thanks. The problem is that my use cases cover both very small and very large amounts of data, so this problem may occur in production as well. In addition, the number of handlers is determined at runtime, so setting up a countdown latch would be a bit tedious.

My current workaround is kind of similar to what you suggested, only I did the waiting part manually. I made all my `EventHandlers` extend a common abstract class which sets a boolean property in their `onStart` method. I add them all to a collection and then wait until all of them set the property.

```java
while (!handlers.stream().allMatch(ObservableEventHandler::isStarted)) {
    try {
        Thread.sleep(100);
    } catch (InterruptedException e) {
        throw new RuntimeException(e);
    }
}
disruptor.shutdown();
```

**Comment by markathomas** [comment]
Would this issue possibly result in a continuous busy-wait loop?  I experienced an issue on a production server this week where CPU was getting hammered by java process.  Running a jstack on the process showed threads in the ```ConsumerRepository.getLastSequenceInChain()``` called from ```Disruptor.hasBacklog()```.  Here is the ST:

```
"processor-9600" #79238 daemon prio=5 os_prio=0 tid=0x00007fa30e943000 nid=0x2011 runnable [0x00007fa30417f000]
   java.lang.Thread.State: RUNNABLE
        at com.lmax.disruptor.dsl.ConsumerRepository.getLastSequenceInChain(ConsumerRepository.java:70)
        at com.lmax.disruptor.dsl.Disruptor.hasBacklog(Disruptor.java:411)
        at com.lmax.disruptor.dsl.Disruptor.shutdown(Disruptor.java:338)
        at com.lmax.disruptor.dsl.Disruptor.shutdown(Disruptor.java:317)
        at reactor.core.processor.Processor.shutdown(Processor.java:115)
        at com.webit360.boxview.ui.data.AbstractEntityContainer.shutdownProcessor(AbstractEntityContainer.java:85)
        at com.webit360.boxview.ui.data.AbstractEntityContainer.onDestroy(AbstractEntityContainer.java:58)
        at com.webit360.boxview.ui.data.AbstractNonUpdatingEntityContainer.destroy(AbstractNonUpdatingEntityContainer.java:121)
        at com.webit360.boxview.ui.data.ContainerUtils.destroyUnmanagedContainer(ContainerUtils.java:39)
        at com.webit360.boxview.ui.dashboard.FacilityDashboardTable.detach(FacilityDashboardTable.java:121)
        at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:520)
        at com.vaadin.ui.AbstractComponentContainer.removeComponent(AbstractComponentContainer.java:225)
        at com.vaadin.ui.AbstractOrderedLayout.removeComponent(AbstractOrderedLayout.java:179)
        at com.webit360.boxview.ui.dashboard.DividedDashboardTable.updateTables(DividedDashboardTable.java:99)
        - locked <0x00000006f2f656d0> (a com.webit360.boxview.ui.dashboard.DividedDashboardTable)
        at com.webit360.boxview.ui.dashboard.DividedDashboardTable.lambda$attach$8637360b$1(DividedDashboardTable.java:111)
        at com.webit360.boxview.ui.dashboard.DividedDashboardTable$$Lambda$227/1304652857.containerItemSetChange(Unknown Source)
        at com.vaadin.data.util.AbstractContainer.fireItemSetChange(AbstractContainer.java:242)
        at com.vaadin.data.util.AbstractContainer.fireItemSetChange(AbstractContainer.java:228)
        at com.webit360.boxview.ui.data.FilterableListContainer.fireItemSetChange(FilterableListContainer.java:117)
        at com.webit360.boxview.ui.data.AbstractNonUpdatingEntityContainer.lambda$reload$3(AbstractNonUpdatingEntityContainer.java:256)
        at com.webit360.boxview.ui.data.AbstractNonUpdatingEntityContainer$$Lambda$114/1342769646.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Comment by mikeb01** [comment]
Sorry for the late response @markathomas that is probably a similar issue.  I would recommend the latch based workaround from above.

**Comment by markathomas** [comment]
thanks @mikeb01 i'll see what i can do as i'm indirectly using disruptor via the Spring Reactor project.  they might have fixed this issue in a newer version.
