### ISSUE TITLE
Hung thread while publishing event

### ISSUE THREAD

**Issue by olamy** [LMAX-Exchange/disruptor#143]
There are some hung threads while publishing event. Is there any wait to have a timeout when publishing event to prevent being stucked?
Logs:
[20/01/16 16:55:32:782 EST] 0000001e ThreadMonitor W   WSVR0605W: Thread "MessageListenerThreadPool : 3" (00000081) has been active for 760752 milliseconds and may be hung.  There is/are 1 thread(s) in total in the server that may be hung.
                at sun.misc.Unsafe.park(Native Method)
                at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:317)
                at com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:136)
                at com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:105)
                at com.lmax.disruptor.RingBuffer.publishEvent(RingBuffer.java:444)
                at com.lmax.disruptor.dsl.Disruptor.publishEvent(Disruptor.java:256)

**Comment by olamy** [comment]
More details:
Operating System and version – SunOS 5.10
App Server name and version – Websphere application server – version 7.0.0.17
JDK used and version - 1.6.0_24

**Comment by mikeb01** [comment]
There isn't anything specific built into the Disruptor, but you can use the non-blocking calls to simulate the same thing.

```Java
boolean published;
do {
    published = ringBuffer.tryPublishEvent(...);
    if (!published && hasTimedOut()) {
        throw new RuntimeException("Timeout");
    }
}
while (!published);
```

You'll need to decide how you want to manage the timeout (counter or grabbing the current time).

As an aside, jdk 1.6.0_24 does have concurrency bugs and you should ensure that you are on the latest version.

**Comment by olamy** [comment]
Thanks for the workaround.
It works fine!
I close this issue and it cannot really be fixed at the disruptor level.
Thanks again!
