### ISSUE TITLE
java.lang.UnsatisfiedLinkError: sun/misc/Unsafe.putOrderedLong(Ljava/lang/Object;JJ)V  at Sequence.<init>(Sequence.java:80)

### ISSUE THREAD

**Issue by linajiang** [LMAX-Exchange/disruptor#184]
i use websphere .
here is the exception stack:
java.lang.UnsatisfiedLinkError: sun/misc/Unsafe.putOrderedLong(Ljava/lang/Object;JJ)V
        at com.lmax.disruptor.Sequence.<init>(Sequence.java:80)
        at com.lmax.disruptor.AbstractSequencer.<init>(AbstractSequencer.java:34)
        at com.lmax.disruptor.MultiProducerSequencer.<init>(MultiProducerSequencer.java:55)
        at com.lmax.disruptor.RingBuffer.createMultiProducer(RingBuffer.java:132)
        at com.lmax.disruptor.RingBuffer.create(RingBuffer.java:200)
        at com.lmax.disruptor.dsl.Disruptor.<init>(Disruptor.java:98)
        at org.apache.logging.log4j.core.async.AsyncLogger.<clinit>(AsyncLogger.java:125)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:200)

how cant i fix this bug

**Comment by mikeb01** [comment]
What version of the JDK are you using?

**Comment by juddgaddie** [comment]
Looks like some versions of IBM J9 do not support sun.misc.Unsafe see: https://groups.google.com/forum/m/#!topic/akka-user/0Z-9_Bmt8p4
