### ISSUE TITLE
Initialize RingBuffer in J9 causes java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by wu-sheng** [LMAX-Exchange/disruptor#188]
Here is the Error stack:
```
8月 8, 2016 18:22:50:995 +0800 [2512 1] com.blueware ERROR: Unable to start oneapm agent: java.lang.UnsatisfiedLinkError: sun/misc/Unsafe.putOrderedLong(Ljava/lang/Object;JJ)V
java.lang.UnsatisfiedLinkError: sun/misc/Unsafe.putOrderedLong(Ljava/lang/Object;JJ)V
	at com.blueware.deps.com.lmax.disruptor.Sequence.<init>(Sequence.java:80) ~[oneapm.jar:2.0]
	at com.blueware.deps.com.lmax.disruptor.AbstractSequencer.<init>(AbstractSequencer.java:35) ~[oneapm.jar:2.0]
	at com.blueware.deps.com.lmax.disruptor.MultiProducerSequencer.<init>(MultiProducerSequencer.java:55) ~[oneapm.jar:2.0]
	at com.blueware.deps.com.lmax.disruptor.RingBuffer.createMultiProducer(RingBuffer.java:136) ~[oneapm.jar:2.0]
	at com.blueware.deps.com.lmax.disruptor.RingBuffer.createMultiProducer(RingBuffer.java:151) ~[oneapm.jar:2.0]
	at com.blueware.deps.com.lmax.disruptor.dsl.Disruptor.<init>(Disruptor.java:118) ~[oneapm.jar:2.0]
	at com.blueware.monitor.collector.client.buffer.TransactionDisruptorBufferService.doStart(TransactionDisruptorBufferService.java:42) ~[oneapm.jar:2.0]
	at com.blueware.monitor.service.AbstractService.start(AbstractService.java:45) ~[oneapm.jar:2.0]
	at com.blueware.monitor.service.ServiceManagerImpl.doStart(ServiceManagerImpl.java:139) ~[oneapm.jar:2.0]
	at com.blueware.monitor.service.AbstractService.start(AbstractService.java:45) ~[oneapm.jar:2.0]
	at com.blueware.monitor.Agent.premain(Agent.java:178) ~[oneapm.jar:2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48) ~[na:1.6.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37) ~[na:1.6.0]
	at java.lang.reflect.Method.invoke(Method.java:600) ~[na:1.6.0]
	at com.blueware.start.StartAgent.startAgent(StartAgent.java:143) [oneapm.jar:2.0]
	at com.blueware.start.StartAgent.premain(StartAgent.java:120) [oneapm.jar:2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48) ~[na:1.6.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37) ~[na:1.6.0]
	at java.lang.reflect.Method.invoke(Method.java:600) ~[na:1.6.0]
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:335) [na:1.6.0]
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:350) [na:1.6.0]
```

We run the application with a `javaagent`, which includes `Disruptor`.

And this is the JVM info:

```shell
C:\Documents and Settings\Administrator>cd C:\apps\IBM\WebSphere\AppServer\java\
bin

C:\apps\IBM\WebSphere\AppServer\java\bin>java.exe -version
java version "1.6.0"
Java(TM) SE Runtime Environment (build pwi3260sr7ifix-20100220_01(SR7+IZ70326))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Windows Server 2003 x86-32 jvmwi3260s
r7-20100219_54049 (JIT enabled, AOT enabled)
J9VM - 20100219_054049
JIT  - r9_20091123_13891
GC   - 20100216_AA)
JCL  - 20091202_01
```

**Comment by juddgaddie** [comment]
See #184 looks like your version of J9 does not have Unsafe. It is required for the Disruptor.

**Comment by wu-sheng** [comment]
Checked, it is caused by some version of J9 1.6... Thanks.
