### ISSUE TITLE
memory leak even a handler is used to clear event

### ISSUE THREAD

**Issue by lujiajing1126** [LMAX-Exchange/disruptor#204]
I use following codes to init Disruptor

```java
Disruptor<PushEvent> disruptor = new Disruptor<>(factory, 1 << bufferSize, threadFactory, ProducerType.MULTI, new BlockingWaitStrategy());
disruptor.handleEventsWithWorkerPool(workHandlers).then(new ClearEventHandler());
disruptor.start();
```

And in the `ClearEventHandler`

```java
public class ClearEventHandler implements EventHandler<PushEvent> {

    @Override
    public void onEvent(PushEvent event, long sequence, boolean endOfBatch) {
        // Failing to call clear here will result in the
        // object associated with the event to live until
        // it is overwritten once the ring buffer has wrapped
        // around to the beginning.
        event.clear(); // just set null
    }
}
```

But in the production environment, some of the instances cannot correctly clear the references.

So that memory leaks. I checked the heap dump and found that.

I wonder if I write the code correctly? Or it is a bug

**Comment by mikeb01** [comment]
What behaviour are you seeing when you have a memory leak.  E.g. is the JVM crashing with an out of memory error.

Would it be possible to post a more complete example that I can run to replicate the behaviour that you are seeing?

**Comment by lujiajing1126** [comment]
The following stacktrace is dumped from a production application:

```
"Thread-154" #208 prio=5 os_prio=0 tid=0x00007f5d8323a000 nid=0x117 runnable [0x00007f5ce8b12000]
   java.lang.Thread.State: RUNNABLE
	at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:56)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:124)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"Thread-153" #207 prio=5 os_prio=0 tid=0x00007f5d83238800 nid=0x116 waiting on condition [0x00007f5ce8c13000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000702ae6750> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"Thread-152" #206 prio=5 os_prio=0 tid=0x00007f5d83237000 nid=0x115 waiting on condition [0x00007f5ce8d14000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000702ae6750> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"Thread-151" #205 prio=5 os_prio=0 tid=0x00007f5d83236000 nid=0x114 waiting on condition [0x00007f5ce90cf000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000702ae6750> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"Thread-149" #203 prio=5 os_prio=0 tid=0x00007f5cdd14c000 nid=0x112 waiting on condition [0x00007f5ce93d2000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000702ae6750> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None
```

Only one of the thread in the worker pool of disruptor was working well while others were all waiting on the same condition. That made events accumulate in the ring buffer which eventually caused the leak.

**Comment by mikeb01** [comment]
Do you see the same issue when using one of the busy wait strategies?  E.g. sleeping or yielding.

**Comment by lujiajing1126** [comment]
@mikeb01 what's the differences between these strategies?

I think my application may focus on low latency. Which strategy is suitable for me?

**Comment by mikeb01** [comment]
BlockingWaitStrategy is best for low CPU usage, but will likely have inconsistent latency.  SleepingWaitStrategy has low impact on the publishing thread but the CPU cost is higher.  BusySpinWaitStrategy and YieldingWaitStrategy are the best for latency but have the highest CPU cost.

**Comment by lujiajing1126** [comment]
I found that all strategies with spin retries could exhaust CPU resources for we normally use 4 cores virtual machines from cloud service provider. What kind of server do you use in the production env? more than 32 cores?

I think `TimeoutBlockingWaitStrategy` may be the best solution for us. I hope it could solve this stuck issue.

btw, what's the differences between MULTI PRODUCER and SINGLE PRODUCER? I understand in multi-threads cases, I should use multi one

**Comment by mikeb01** [comment]
We run on all physical hardware.  The number of CPUs differs from service to service, but when we are using busy spin we ensure that we have fewer threads than CPU cores.

The MultiProducer support events being published from multiple threads.  This should be your default.  If you **know** that you only have a single thread publishing to the ring buffer then you can use SingleProducer for increased performance.

Are you able to post a snippet of your publishing code.

**Comment by lujiajing1126** [comment]
Thank you. Eventually, I have found the reason. It was caused essentially by exceptions thrown in the event handler.

I think the exception handle mechanism should be improved. It will greatly hurt the performance and bring about unexpected consequences.
