### ISSUE TITLE
100% CPU is used and 90% threads In timed_waiting are blocked on thrMultiProducerSequencer.next

### ISSUE THREAD

**Issue by duguyixiaono1** [LMAX-Exchange/disruptor#209]
Recently, the strange problem occasionally occur in our prod environment of a service:
1) all the 4 core CPUs are 100% busy
2) the number of threads in timed_waiting rise sharply, and the stack is shown as follows:

`
"********" #430 prio=5 os_prio=0 tid=0x00007f5b8c89e800 nid=0x313a runnable [0x00007f5b2fc38000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
        at com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:136)
        at com.lmax.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:105)
        at com.lmax.disruptor.RingBuffer.publishEvent(RingBuffer.java:502)
        at org.apache.logging.log4j.core.async.AsyncLoggerConfigHelper.callAppendersFromAnotherThread(AsyncLoggerConfigH
elper.java:342)
        at org.apache.logging.log4j.core.async.AsyncLoggerConfig.callAppenders(AsyncLoggerConfig.java:114)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:738)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:708)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:193)
        ...
`
3) no BatchEventProcessor threads are running

our prod env:
Linux 2.6.32-431.20.3.el6.mt20161028.x86_64
disruptor 3.3.0
log4j 2.3

is there any hints provided? thx

**Comment by mikeb01** [comment]
This looks like the Log4J ring buffer is full.  Is it possible that the thread writing to the database has exited or running slowly?

**Comment by duguyixiaono1** [comment]
@mikeb01 
No thread writing to db, while one appender writing to kafka. 
It looks like [this problem](https://issues.apache.org/jira/browse/LOG4J2-1324), and has nothing to do with the disruptor.
I try to upgrade log4j2 or implement exception handler.
I close this issue firstly.
thx mikeb01
