### ISSUE TITLE
SleepingWaitStrategy causing almost 98% CPU with one consumer when idle on 64 bit Linux

### ISSUE THREAD

**Issue by Stephenkk204** [LMAX-Exchange/disruptor#273]
Hi team,
We use 15 consumers and every consumer cause almost 97% cpu even the the application is idle.
the current version info:
JRE:
OpenJDK Runtime Environment (build 1.8.0_212)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
Disruptor:disruptor-3.4.2

OS：64 bit linux

thread cpu info:
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 51749 ossuser   20   0 9635744   2.8g     32 R  98.7  10.1 174:57.50 java
 51761 ossuser   20   0 9635744   2.8g     32 R  98.7  10.1 174:46.85 java
 51747 ossuser   20   0 9635744   2.8g     32 R  98.4  10.1 174:50.25 java
 51748 ossuser   20   0 9635744   2.8g     32 R  98.4  10.1 174:45.82 java
 51758 ossuser   20   0 9635744   2.8g     32 R  98.4  10.1 174:58.06 java
 51752 ossuser   20   0 9635744   2.8g     32 R  98.0  10.1 175:06.28 java
 51753 ossuser   20   0 9635744   2.8g     32 R  97.7  10.1 174:47.16 java
 51759 ossuser   20   0 9635744   2.8g     32 R  97.7  10.1 174:47.44 java

stack trace:
"Thread-9147" #40798 prio=6 os_prio=0 tid=0x0000aaaae7aae000 nid=0xca25 runnable [0x0000fffed7844000]
   java.lang.Thread.State: RUNNABLE
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at com.lmax.disruptor.SleepingWaitStrategy.applyWaitMethod(SleepingWaitStrategy.java:92)
	at com.lmax.disruptor.SleepingWaitStrategy.waitFor(SleepingWaitStrategy.java:65)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x000000073a1a98d8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Thread-9159" #40810 prio=6 os_prio=0 tid=0x0000aaaae70be800 nid=0xca31 runnable [0x0000fffee6c44000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at com.lmax.disruptor.SleepingWaitStrategy.applyWaitMethod(SleepingWaitStrategy.java:92)
	at com.lmax.disruptor.SleepingWaitStrategy.waitFor(SleepingWaitStrategy.java:65)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x000000073a233ba0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by mikeb01** [comment]
I've noticed on newer Linux kernels, if the sleep time is too short then the system doesn't actually park the thread.  I would recommend experimenting with specifying the sleepTimeNs on the SleepingWaitStrategy to see if larger values will allow the thread to idle.

**Comment by Stephenkk204** [comment]
thanks

**Comment by mikeb01** [comment]
Closing due to no further follow up.
