### ISSUE TITLE
Cannot run JMH via gradle from command line

### ISSUE THREAD

**Issue by Palmr** [LMAX-Exchange/disruptor#337]
When attempting a `clean jmh` run via gradle it throws an error about not being able to touch the report file.

In the gradle task for jmh we already have an attempt to make sure the directory is there but perhaps this isn't working.

```groovy
    def resultFile = file("build/reports/jmh/result.${format}")
    resultFile.parentFile.mkdirs()
```

After an attempted run there is no `reports` directory under build.

```
$ ./gradlew clean jmh

> Task :jmh FAILED
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.openjdk.jmh.util.Utils (file:/home/nick/.gradle/caches/modules-2/files-2.1/org.openjdk.jmh/jmh-core/1.26/3a60bc5f3b6204cc52139e4cb8967f4209e115e3/jmh-core-1.26.jar) to field java.io.PrintStream.charOut
WARNING: Please consider reporting this to the maintainers of org.openjdk.jmh.util.Utils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR: org.openjdk.jmh.runner.RunnerException: Can not touch the result file: /home/nick/git-projects/disruptor/build/reports/jmh/result.json
        at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:263)
        at org.openjdk.jmh.runner.Runner.run(Runner.java:210)
        at org.openjdk.jmh.Main.main(Main.java:71)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jmh'.
> Process 'command '/usr/lib/jvm/java-11-openjdk/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
4 actionable tasks: 4 executed
```

**Comment by swarren12** [comment]
Just took a quick look at this.

`File.mkdirs()` returns a `boolean` for success or failure - for some reason this seems to be returning `false`?

**Comment by swarren12** [comment]
> Just took a quick look at this.
> 
> `File.mkdirs()` returns a `boolean` for success or failure - for some reason this seems to be returning `false`?

Actually, scratch this - it also returns `false` if the directory already exists...

**Comment by Palmr** [comment]
The following works for me:

```
$ ./gradlew clean

BUILD SUCCESSFUL in 535ms
1 actionable task: 1 executed

$ mkdir -p build/reports/jmh
$ ./gradlew jmh

> Task :jmh
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.openjdk.jmh.util.Utils (file:/home/nick/.gradle/caches/modules-2/files-2.1/org.openjdk.jmh/jmh-core/1.26/3a60bc5f3b6204cc52139e4cb8967f4209e115e3/jmh-core-1.26.jar) to field java.io.PrintStream.charOut
WARNING: Please consider reporting this to the maintainers of org.openjdk.jmh.util.Utils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
# JMH version: 1.26
# VM version: JDK 11.0.8, OpenJDK 64-Bit Server VM, 11.0.8+10
# VM invoker: /usr/lib/jvm/java-11-openjdk/bin/java
# VM options: -Xmx256m -Xms256m -XX:MaxDirectMemorySize=1g -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant
# Warmup: 5 iterations, 1 s each
# Measurement: 5 iterations, 1 s each
# Timeout: 10 min per iteration
# Threads: 5 threads (1 group; 1x "incrementValue2", 1x "read1", 1x "read2", 1x "setValue1Opaque", 1x "setValue1Volatile" in each group), will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: com.lmax.disruptor.SequenceBenchmark.AtomicLong

# Run progress: 0.00% complete, ETA 00:05:00
# Fork: 1 of 5
<===========--> 85% EXECUTING [5s]

...etc.
```

**Comment by swarren12** [comment]
Okay, I think I know what's going on.

The `mkdirs()` is happening during the Gradle configuration phase; so in the original run the order was: `mkdirs()` -> `clean` -> `jmh`.

The working case would be evaluated as `mkdirs()` (probably) -> `clean` -> `mkdirs()` -> `jmh`.

The fix here would be to put the `mkdirs()` call inside a `doFirst { }` block, e.g.

```
doFirst {
    resultFile.parentFile.mkdirs()
}
```
