### ISSUE TITLE
Java 21 and log4j

### ISSUE THREAD

**Issue by jkvargas** [LMAX-Exchange/disruptor#465]
**Describe the bug**
So I on my app I executed the following final static Logger logger = LogManager.getLogger();
and I got an exception that seems related to LMAX,
maybe you guys can help me to understand if this is LMAX issue or Log4j

**Desktop (please complete the following information):**
 - OS: Linux
 - JVM Version Correto 21

**Additional context**

```
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/Unsafe
    at com.lmax.disruptor.util.Util$1.run(Util.java:103)
    at com.lmax.disruptor.util.Util$1.run(Util.java:100)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.lmax.disruptor.util.Util.<clinit>(Util.java:109)
    at com.lmax.disruptor.RingBufferFields.<clinit>(RingBuffer.java:34)
    at com.lmax.disruptor.dsl.Disruptor.<init>(Disruptor.java:137)
    at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor.start(AsyncLoggerConfigDisruptor.java:220)
    at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:312)
    at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
    at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
    at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
    at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
    at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
    at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
    at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
    at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
    at Main.<clinit>(Main.java:25)
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
```

**Comment by Palmr** [comment]
Disruptor v4 no longer uses `sun.misc.unsafe` and so will be needed.

Unfortunately Log4J2 does not yet have support for the latest version, there is an open PR however that you can track: https://github.com/apache/logging-log4j2/pull/1937
